# Generated by Django 5.2.8 on 2025-11-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='auto_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
